name: prepare_cv

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  convert_to_docx:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: ls -lR
      - uses: docker://pandoc/core:2.9
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            -r markdown
            -w docx
            --output=cv.docx
            cv.md # gets appended to pandoc command
      - uses: actions/upload-artifact@master
        with:
          name: cv.docx

  convert_to_pdf:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: cd /github/workspace
      - uses: docker:///latex:2.9
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            -r markdown
            -w pdf
            --pdf-engine=context
            --output=cv.pdf
            cv.md # gets appended to pandoc command
      - uses: actions/upload-artifact@master
        with:
          name: cv.pdf
