name: prepare_cv

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  convert_to_docx:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core:2.9
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            -w docx
            --output=cv.docx
            cv.md
      - run : ls -l
      - uses: EndBug/add-and-commit@v4
        with:
          add: cv.docx
          message: 'Add docx cv'
        env:   # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
